import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

// Dashboard UI용 메이저 폰트 - 다양한 웨이트 지원
const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    display: 'swap',
});

const stripe = localFont({
    src: './fonts/60sSTRIPE.ttf',
    variable: '--font-stripe',
});

const bokeh = localFont({
    src: './fonts/BOKEH.ttf',
    variable: '--font-bokeh',
});

const nyangi = localFont({
    src: './fonts/Nyangi-W-v1.0.woff2',
    variable: '--font-nyangi',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${stripe.variable} ${bokeh.variable} ${nyangi.variable} antialiased`}
            >
                <ErrorBoundary>{children}</ErrorBoundary>
                <Toaster />
            </body>
        </html>
    );
}
